---
#
# LazyBytez Desktop configurator playbook
#
# Configures an Ubuntu Desktop system with Gnome.
# Also handles installation of common applications.
#

- name: Lazy Bytez Desktop Configurator
  hosts: localhost
  become: true
  
  roles:
    - common-software
    - webarchitect609.google_chrome
    - geerlingguy.nodejs
    - ocha.yarn
    - user-handling
    - geerlingguy.php
    - geerlingguy.php-versions
    - darkwizard242.shellcheck
    - geerlingguy.docker
    - gantsign.keyboard
    - robertdebock.locale