---
#
# LazyBytez Desktop configurator playbook
#
# Configures an Ubuntu Desktop system with Gnome to match our preferred look and feel.
# Also handles installation of common applications.
#

- name: Lazy Bytez Desktop Configurator
  hosts: localhost
  become: true
  
  roles:
    - common-software
    - lean_delivery.java
    - geerlingguy.nodejs
    - ocha.yarn
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.php-xdebug
    - geerlingguy.php-redis
    - geerlingguy.php-pgsql
    - geerlingguy.php-pear
    - geerlingguy.php-pecl
    - darkwizard242.shellcheck
    - docker
    - psh
    - gantsign.keyboard
    - robertdebock.locale

  tasks:
    - name: Install Golang
      snap:
        name: "go"
        classic: true
        state: present
      tags: [ 'software' ]
