---
#
# Ansible Galaxy requirements
#
roles:
  - lean_delivery.java
  - geerlingguy.nodejs
  - ocha.yarn
  - darkwizard242.shellcheck
  - geerlingguy.php
  - geerlingguy.php-versions
  - gantsign.keyboard
  - robertdebock.locale
  - geerlingguy.docker
  - webarchitect609.google_chrome
