---
#
# Install the PSH shell if not already done
#
# Installation is only run if PSH is not cloned locally.
#
- name: Clone PSH repository
  become: false
  git:
    repo: https://github.com/pascal-zarrad/psh.git
    dest: "/home/{{ lookup('env', 'USER') }}/.lazybytez-theme/psh"
    clone: true
    update: true
  register: psh_repository_result
  tags: [ 'software', 'psh' ]
- name: Install PSH if necessary
  command: "./install.sh --unattended"
  args:
    chdir: "/home/{{ lookup('env', 'USER') }}/.lazybytez-theme/psh"
  when: psh_repository_result.changed
  tags: [ 'software', 'psh' ]
