---
#
# Install Docker on servers
#
- name: Add Docker repository GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable
    update_cache: true
- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes
    state: latest
- name: Install Docker CE CLI
  apt:
    name: docker-ce-cli
    update_cache: yes
    state: latest
- name: Install containerd.io
  apt:
    name: containerd.io
    update_cache: yes
    state: latest
